name: Deploy static site to GitHub Pages

# Trigger on pushes to your main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    # Runs the job on the latest Ubuntu VM
    runs-on: ubuntu-latest

    # Grant only the permissions we need
    permissions:
      pages: write       # to publish your site
      id-token: write    # required by configure-pages

    steps:
      # 1. Check out your repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configure GitHub Pages
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      # 3. Upload the site content as an artifact
      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@v3
        with:
          # Publish everything at repo root (index.html, styles.css, etc.)
          path: .

      # 4. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
